### ISSUE TITLE
Cannot disable confirmation prompts when publishing

### ISSUE THREAD

**Issue by zabihexes** [deno911/eggs#2]
## 🐛 Bug Report

Cannot disable confirmation prompts when publishing.

## To Reproduce

`eggy publish -Y`

## Expected behavior

Version gets published without me confirming anything.

## Actual Behavior

`error: illegal option: -Y`

## Environment

- Eggs version: https://x.nest.land/eggy@0.3.50/cli.ts
- Deno version:
```
deno 1.29.2 (release, x86_64-unknown-linux-gnu)
v8 10.9.194.5
typescript 4.9.4
```
- Operating system and version: devcontainer - `mcr.microsoft.com/vscode/devcontainers/base:debian-10`

**Comment by zabihexes** [comment]
I can do `echo Y | eggy publish` as a workaround, but that is not ideal.

**Comment by nberlette** [comment]
I just noticed this behavior myself. I'll throw together a fix for it ASAP and will close this out once it's released. Also, sorry for the delayed reply. Thanks!
